### ISSUE TITLE
Displaying current best during the computation

### ISSUE THREAD

**Issue by pogudingleb** [AndreyBychkov/QBee#4]
In addition to `Nodes traversed` it would be very helpful if the `current optimal order` would be displayed.

**Comment by AndreyBychkov** [comment]
Added in 6e1b5e81e28640b9de88942fdf45ed859a6768d0

Now we have the progress bar similar to the example below:
```
Nodes processed: 123 nodes [00:00, 777.60 nodes/s, Current best order = 5]
```
