### ISSUE TITLE
Return current best on keyboard interruption

### ISSUE THREAD

**Issue by pogudingleb** [AndreyBychkov/QBee#5]
It would be great if there will be some hot-key (maybe just Ctrl + C) to stop the computation and return the currently optimal quadratization (maybe not a globally optimal one).

**Comment by AndreyBychkov** [comment]
Added feature in a1aa865215f433548ac6c68dab2c227320d51782

It's quite a messy solution with the global variable in it, but it was much more performant than using try-except with KeyboardInterruption.
